spring:
  datasource:
    url: jdbc:mysql://localhost:33306/thread_demo?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user
    password: 7475
    driver-class-name: com.mysql.cj.jdbc.Driver
